/**
 * @file gap.h
 * ESP32 GAP (Generic Access Profile) types
 *
 * Provides the same GapEvent types as STM32 for bt_service compatibility.
 * On ESP32, events are generated by the furi_hal_bt bridge layer.
 */

#pragma once

#include "profile_interface.h"

#include <stdbool.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define GAP_KEY_SIZE 0x10

typedef struct {
    uint8_t erk[GAP_KEY_SIZE]; /**< Encryption Root Key */
    uint8_t irk[GAP_KEY_SIZE]; /**< Identity Root Key */
} GapRootSecurityKeys;

typedef enum {
    GapEventTypeConnected,
    GapEventTypeDisconnected,
    GapEventTypeStartAdvertising,
    GapEventTypeStopAdvertising,
    GapEventTypePinCodeShow,
    GapEventTypePinCodeVerify,
    GapEventTypeUpdateMTU,
    GapEventTypeBeaconStart,
    GapEventTypeBeaconStop,
} GapEventType;

typedef union {
    uint32_t pin_code;
    uint16_t max_packet_size;
} GapEventData;

typedef struct {
    GapEventType type;
    GapEventData data;
} GapEvent;

typedef bool (*GapEventCallback)(GapEvent event, void* context);

typedef enum {
    GapStateUninitialized,
    GapStateIdle,
    GapStateStartingAdv,
    GapStateAdvFast,
    GapStateAdvLowPower,
    GapStateConnected,
} GapState;

// Full GapExtraBeaconConfig definition in extra_beacon.h
#include <extra_beacon.h>

/** Callback fired when BLE key storage changes (STM32: NVM SRAM).
 *  On ESP32, Bluedroid manages bonding via NVS — this is never called. */
typedef void (*BleGlueKeyStorageChangedCallback)(uint8_t* addr, uint16_t size, void* context);

#ifdef __cplusplus
}
#endif
