#!/usr/bin/env bash
# =============================================================================
# Flash script — __BOARD_NAME__ (__CHIP__)
# Generated by CI for this specific build.
#
# Usage:
#   chmod +x flash_linux.sh            # make executable (first time only)
#   ./flash_linux.sh                   # auto-detect port
#   ./flash_linux.sh /dev/ttyUSB0      # explicit port
#   ./flash_linux.sh /dev/ttyUSB0 115200   # explicit port + custom baud
#
# Requirements: esptool  (pip install esptool)
# =============================================================================
set -euo pipefail

CHIP="__CHIP__"
FLASH_SIZE="__FLASH_SIZE__"
PORT="${1:-}"
BAUD="${2:-460800}"
DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
die()  { echo -e "${RED}[ERROR] $*${NC}" >&2; exit 1; }
ok()   { echo -e "${GREEN}[OK]${NC}  $*"; }
info() { echo -e "${CYAN}  --> $*${NC}"; }
warn() { echo -e "${YELLOW}[WARN] $*${NC}"; }

# ---- find esptool -----------------------------------------------------------
find_esptool() {
    # 1. standalone binary
    if command -v esptool >/dev/null 2>&1; then
        printf '%s' "esptool"; return 0
    fi
    # 2. esptool.py on PATH
    if command -v esptool.py >/dev/null 2>&1; then
        printf '%s' "esptool.py"; return 0
    fi
    # 3. python3 module
    if python3 -m esptool version >/dev/null 2>&1; then
        printf '%s' "python3 -m esptool"; return 0
    fi
    # 4. python module
    if python -m esptool version >/dev/null 2>&1; then
        printf '%s' "python -m esptool"; return 0
    fi
    # 5. bundled with a local ESP-IDF install
    for idf_root in "${IDF_PATH:-__UNSET__}" "$HOME/esp/esp-idf" "/opt/esp-idf"; do
        local script="$idf_root/components/esptool_py/esptool/esptool.py"
        if [[ "$idf_root" != "__UNSET__" && -f "$script" ]]; then
            printf '%s' "python3 $script"; return 0
        fi
    done
    return 1
}

ESPTOOL=$(find_esptool) || {
    echo ""
    die "esptool not found.
  Install it with:  pip install esptool
  Then re-run this script."
}

# ---- find port --------------------------------------------------------------
if [[ -z "$PORT" ]]; then
    # Try common device nodes; glob so wildcards expand correctly
    for pattern in \
        /dev/ttyUSB0 /dev/ttyUSB1 /dev/ttyUSB2 \
        /dev/ttyACM0 /dev/ttyACM1 \
        /dev/cu.usbserial-* /dev/cu.SLAB_USBtoUART* /dev/cu.wchusbserial* \
        /dev/cu.usbmodem*; do
        # shellcheck disable=SC2206
        matches=( $pattern )   # intentional glob expansion
        for m in "${matches[@]}"; do
            [[ -c "$m" ]] && PORT="$m" && break 2
        done
    done
fi

[[ -z "$PORT" ]] && die \
    "No serial port found automatically.
  Connect the board and pass the port:  ./flash_linux.sh /dev/ttyUSB0"

# ---- check binaries are present ---------------------------------------------
BOOTLOADER="$DIR/bootloader/bootloader.bin"
PARTITIONS="$DIR/partition_table/partition-table.bin"
FIRMWARE="$DIR/furi_esp32.bin"

[[ -f "$BOOTLOADER" ]] || die "Missing bootloader: $BOOTLOADER"
[[ -f "$PARTITIONS" ]] || die "Missing partition table: $PARTITIONS"
[[ -f "$FIRMWARE"   ]] || die "Missing firmware: $FIRMWARE"

# ---- print summary ----------------------------------------------------------
echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  Flipper ESP32 — Flash Utility${NC}"
echo -e "${GREEN}========================================${NC}"
info "Board      : __BOARD_NAME__"
info "Chip       : $CHIP"
info "Port       : $PORT"
info "Baud       : $BAUD"
info "Flash size : $FLASH_SIZE"
echo ""
info "Bootloader      @ 0x00000  $BOOTLOADER"
info "Partition table @ 0x08000  $PARTITIONS"
info "Firmware        @ 0x10000  $FIRMWARE"
echo ""

# ---- flash ------------------------------------------------------------------
# Run esptool — split ESPTOOL into words so multi-word invocations work
# shellcheck disable=SC2086
$ESPTOOL \
    --chip   "$CHIP"  \
    --port   "$PORT"  \
    --baud   "$BAUD"  \
    --before default_reset \
    --after  hard_reset    \
    write_flash            \
        --flash_mode  dio  \
        --flash_freq  80m  \
        --flash_size  "$FLASH_SIZE" \
        0x00000 "$BOOTLOADER" \
        0x08000 "$PARTITIONS" \
        0x10000 "$FIRMWARE"

echo ""
ok "Flash complete!  __BOARD_NAME__ is booting."
echo ""
