@echo off
:: =============================================================================
:: Flash script — __BOARD_NAME__ (__CHIP__)
:: Generated by CI for this specific build.
::
:: Usage:
::   flash_windows.bat                    auto-detect COM port
::   flash_windows.bat COM3               explicit port
::   flash_windows.bat COM3 115200        explicit port + custom baud
::
:: Requirements: esptool  (pip install esptool)
::               Python 3 must be on PATH
:: =============================================================================

setlocal enabledelayedexpansion

set "CHIP=__CHIP__"
set "FLASH_SIZE=__FLASH_SIZE__"
set "BOARD=__BOARD_NAME__"

:: %~dp0 always ends with \, strip it for consistent concatenation
set "DIR=%~dp0"
if "%DIR:~-1%"=="\" set "DIR=%DIR:~0,-1%"

set "ARG_PORT=%~1"
set "ARG_BAUD=%~2"
if "%ARG_BAUD%"=="" set "ARG_BAUD=460800"

:: ---- locate esptool --------------------------------------------------------
set "ESPTOOL="

where esptool     >nul 2>&1 && set "ESPTOOL=esptool"     && goto :esptool_found
where esptool.py  >nul 2>&1 && set "ESPTOOL=esptool.py"  && goto :esptool_found

python  -c "import esptool" >nul 2>&1 && set "ESPTOOL=python -m esptool"  && goto :esptool_found
python3 -c "import esptool" >nul 2>&1 && set "ESPTOOL=python3 -m esptool" && goto :esptool_found

echo.
echo [ERROR] esptool not found.
echo         Install it: pip install esptool
echo         Make sure Python is on your PATH, then run this script again.
echo.
pause
exit /b 1
:esptool_found

:: ---- auto-detect COM port --------------------------------------------------
set "PORT=%ARG_PORT%"
if not "%PORT%"=="" goto :port_ready

echo Auto-detecting COM port...

:: Ask WMI for serial ports matching common USB-Serial bridge descriptions.
:: The FOR /F trick strips the "DeviceID=" prefix and trims whitespace.
for /f "usebackq tokens=2 delims==" %%A in (
    `wmic path Win32_SerialPort where "(Description like '%%CP210%%') or (Description like '%%CH340%%') or (Description like '%%FTDI%%') or (Description like '%%USB Serial%%') or (Description like '%%USB-SERIAL%%')" get DeviceID /value 2^>nul`
) do (
    :: %%A may contain a trailing carriage return — trim it
    set "RAWPORT=%%A"
    set "PORT=!RAWPORT: =!"
    if not "!PORT!"=="" goto :port_ready
)

:: Fallback: probe COM3-COM20 with MODE (MODE requires the port to exist)
for /l %%N in (3,1,20) do (
    mode COM%%N >nul 2>&1 && set "PORT=COM%%N" && goto :port_ready
)

echo [ERROR] No COM port detected automatically.
echo         Connect the board, then pass the port:  flash_windows.bat COM3
echo.
pause
exit /b 1
:port_ready

:: ---- verify binaries -------------------------------------------------------
set "BOOTLOADER=%DIR%\bootloader\bootloader.bin"
set "PARTITIONS=%DIR%\partition_table\partition-table.bin"
set "FIRMWARE=%DIR%\furi_esp32.bin"

if not exist "%BOOTLOADER%" (
    echo [ERROR] Missing bootloader:       %BOOTLOADER%
    pause & exit /b 1
)
if not exist "%PARTITIONS%" (
    echo [ERROR] Missing partition table:  %PARTITIONS%
    pause & exit /b 1
)
if not exist "%FIRMWARE%" (
    echo [ERROR] Missing firmware:         %FIRMWARE%
    pause & exit /b 1
)

:: ---- print summary ---------------------------------------------------------
echo.
echo ========================================
echo   Flipper ESP32 -- Flash Utility
echo ========================================
echo   Board      : %BOARD%
echo   Chip       : %CHIP%
echo   Port       : %PORT%
echo   Baud       : %ARG_BAUD%
echo   Flash size : %FLASH_SIZE%
echo.
echo   Bootloader      @ 0x00000  %BOOTLOADER%
echo   Partition table @ 0x08000  %PARTITIONS%
echo   Firmware        @ 0x10000  %FIRMWARE%
echo.

:: ---- flash -----------------------------------------------------------------
%ESPTOOL% ^
    --chip   %CHIP%     ^
    --port   %PORT%     ^
    --baud   %ARG_BAUD% ^
    --before default_reset ^
    --after  hard_reset    ^
    write_flash            ^
        --flash_mode  dio  ^
        --flash_freq  80m  ^
        --flash_size  %FLASH_SIZE% ^
        0x00000 "%BOOTLOADER%" ^
        0x08000 "%PARTITIONS%" ^
        0x10000 "%FIRMWARE%"

if %ERRORLEVEL% neq 0 (
    echo.
    echo [ERROR] Flash failed. Check the cable and try again.
    echo         If the board is not entering bootload mode automatically,
    echo         hold the BOOT button while plugging in USB, then re-run.
    echo.
    pause
    exit /b 1
)

echo.
echo [OK]  Flash complete!  %BOARD% is booting.
echo.
pause
